# Generated by Django 3.2.6 on 2024-12-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaña',
            new_name='Campana',
        ),
        migrations.RenameField(
            model_name='campana',
            old_name='id_campaña',
            new_name='id_campana',
        ),
        migrations.RenameField(
            model_name='campana',
            old_name='motivo_bajaCampaña',
            new_name='motivo_bajaCampana',
        ),
        migrations.RenameField(
            model_name='campana',
            old_name='nombre_campaña',
            new_name='nombre_campana',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='contraseña',
            new_name='contrasena',
        ),
        migrations.RenameField(
            model_name='genera',
            old_name='id_campaña',
            new_name='id_campana',
        ),
        migrations.AlterUniqueTogether(
            name='genera',
            unique_together={('id_campana', 'id_gasto')},
        ),
    ]
