# Generated by Django 3.2.6 on 2025-01-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20241211_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='id_campana',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
