# Generated by Django 3.2.6 on 2023-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230728_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
