# Generated by Django 3.2.6 on 2025-01-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_campana_id_campana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='motivo_bajaCampana',
        ),
    ]
